services:
  - type: web
    name: prepedge-api
    env: docker
    plan: free
    healthCheckPath: /api/interview/topics
    envVars:
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: GROQ_API_KEY
        sync: false
