import React, { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { Brain, Sparkles, ArrowRight, Zap, Shield, Star, ChevronDown, CheckCircle, Users, Code2, Layers, Database, Braces, Terminal, Plane } from 'lucide-react';

/* ── Animated background canvas ── */
function StarField() {
  const ref = useRef();
  useEffect(() => {
    const canvas = ref.current;
    const ctx = canvas.getContext('2d');
    let raf;
    const resize = () => { canvas.width = window.innerWidth; canvas.height = window.innerHeight; };
    resize();
    window.addEventListener('resize', resize);
    const stars = Array.from({ length: 160 }, () => ({
      x: Math.random() * canvas.width, y: Math.random() * canvas.height,
      r: Math.random() * 1.2 + 0.2, o: Math.random(), s: Math.random() * 0.005 + 0.001,
    }));
    const draw = () => {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      stars.forEach(s => {
        s.o += s.s; if (s.o > 1 || s.o < 0) s.s *= -1;
        ctx.beginPath(); ctx.arc(s.x, s.y, s.r, 0, Math.PI * 2);
        ctx.fillStyle = `rgba(167,139,250,${s.o * 0.8})`; ctx.fill();
      });
      raf = requestAnimationFrame(draw);
    };
    draw();
    return () => { cancelAnimationFrame(raf); window.removeEventListener('resize', resize); };
  }, []);
  return <canvas ref={ref} style={{ position: 'absolute', inset: 0, zIndex: 0, pointerEvents: 'none' }} />;
}

/* ── Floating Tech Symbols ── */
function FloatingSymbols() {
  const symbols = [
    { icon: <Code2 size={24} />, x: '15%', y: '25%', delay: '0s', dur: '6s', color: '#8b5cf6' },
    { icon: <Database size={24} />, x: '85%', y: '30%', delay: '1s', dur: '8s', color: '#06b6d4' },
    { icon: <Braces size={28} />, x: '10%', y: '65%', delay: '2s', dur: '7s', color: '#f59e0b' },
    { icon: <Terminal size={24} />, x: '88%', y: '70%', delay: '0.5s', dur: '6.5s', color: '#10b981' },
    { icon: <span style={{ fontSize: 24, fontWeight: 800 }}>{'</>'}</span>, x: '25%', y: '80%', delay: '3s', dur: '7s', color: '#ec4899' },
    { icon: <span style={{ fontSize: 32, fontWeight: 600 }}>+</span>, x: '75%', y: '20%', delay: '1.5s', dur: '5s', color: '#f97316' },
    { icon: <span style={{ fontSize: 40, fontWeight: 300 }}>-</span>, x: '20%', y: '45%', delay: '2.5s', dur: '8s', color: '#8b5cf6' },
    { icon: <Brain size={28} />, x: '80%', y: '50%', delay: '0.8s', dur: '7.5s', color: '#38bdf8' }
  ];

  return (
    <div style={{ position: 'absolute', inset: 0, zIndex: 0, pointerEvents: 'none', overflow: 'hidden' }}>
      {symbols.map((s, i) => (
        <div key={i} style={{
          position: 'absolute',
          left: s.x,
          top: s.y,
          color: s.color,
          opacity: 0.4,
          animation: `float-symbol ${s.dur} ease-in-out infinite alternate`,
          animationDelay: s.delay,
          filter: 'drop-shadow(0 0 10px rgba(0,0,0,0.1))'
        }}>
          {s.icon}
        </div>
      ))}

      {/* ── Airplane flying left to right ── */}
      <div style={{
        position: 'absolute',
        top: '15%',
        color: 'var(--primary-light)',
        opacity: 0.3,
        animation: 'fly-plane 25s linear infinite',
        pointerEvents: 'none',
        filter: 'drop-shadow(0 0 10px rgba(139,92,246,0.2))'
      }}>
        <Plane size={32} style={{ transform: 'rotate(45deg)' }} />
      </div>
    </div>
  );
}

const features = [
  { icon: Brain, title: 'AI-Generated Questions', desc: 'Get real interview questions generated by LLMs, tuned for your specific tech stack and target companies.', color: '#8b5cf6' },
  { icon: Zap, title: 'Multiple Topics at Once', desc: 'Input up to 3 topics in one go. Get a comprehensive question bank covering DSA, System Design, Frameworks & more.', color: '#06b6d4' },
  { icon: Shield, title: 'Company-Targeted Prep', desc: 'Specify target companies like Google, Amazon, Meta to get questions aligned with their known interview style.', color: '#f59e0b' },
  { icon: Layers, title: 'Difficulty Graded', desc: 'Questions come tagged Easy, Medium, or Hard so you can pace your prep and focus where you need to grow.', color: '#10b981' },
  { icon: Code2, title: 'Detailed Answers', desc: 'Every question ships with a model answer, not just hints. Learn exactly what interviewers want to hear.', color: '#ec4899' },
  { icon: Star, title: 'Instant & Always Fresh', desc: 'No stale question banks. Questions are generated on-demand so content stays relevant to current interviews.', color: '#f97316' },
];

const steps = [
  { num: '01', title: 'Create Your Account', desc: 'Sign up in seconds. No credit card needed.' },
  { num: '02', title: 'Pick Your Topics', desc: 'Enter up to 3 topics: React, System Design, Python, SQL…' },
  { num: '03', title: 'Add Target Companies', desc: 'Optional: specify companies to personalize difficulty & style.' },
  { num: '04', title: 'Get Interview-Ready', desc: 'Study AI-generated Q&A, review model answers, and ace the interview.' },
];

const stats = [
  { label: 'Topics Supported', value: '50+' },
  { label: 'Questions Generated', value: '10K+' },
  { label: 'Success Rate', value: '94%' },
  { label: 'Companies Covered', value: '200+' },
];

export default function LandingPage() {
  const { user } = useAuth();

  return (
    <div style={{ background: 'var(--bg-900)' }}>
      {/* ── HERO ── */}
      <section style={{ position: 'relative', minHeight: '100vh', display: 'flex', alignItems: 'center', overflow: 'hidden' }}>
        <StarField />
        <FloatingSymbols />
        {/* Orbs */}
        <div className="orb orb-purple" style={{ width: 700, height: 700, top: '-20%', left: '-15%', opacity: 0.5 }} />
        <div className="orb orb-cyan" style={{ width: 500, height: 500, bottom: '-10%', right: '-10%', opacity: 0.4 }} />

        <div className="container" style={{ position: 'relative', zIndex: 1, textAlign: 'center', paddingTop: 100 }}>
          {/* Badge */}
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '8px 20px', borderRadius: 999, background: 'rgba(124,58,237,0.12)', border: '1px solid rgba(139,92,246,0.3)', marginBottom: 32, animation: 'fadeInDown 0.6s ease' }}>
            <Sparkles size={14} color="#a78bfa" />
            <span style={{ fontSize: '0.85rem', color: '#a78bfa', fontWeight: 600 }}>Powered by Groq + Llama 3</span>
          </div>

          <h1 style={{ fontSize: 'clamp(2.8rem, 7vw, 5.5rem)', fontWeight: 900, letterSpacing: '-2px', marginBottom: 24, lineHeight: 1.05 }}>
            Crush Your Next<br />
            <span className="gradient-text">Tech Interview</span><br />
            with AI Precision
          </h1>

          <p style={{ fontSize: 'clamp(1rem, 2.5vw, 1.25rem)', color: 'var(--text-300)', maxWidth: 600, margin: '0 auto 48px', lineHeight: 1.7 }}>
            Generate hyper-relevant, company-specific interview questions in seconds. Backed by real LLM intelligence, not stale question banks.
          </p>

          <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap', marginBottom: 60 }}>
            {user ? (
              <Link to="/dashboard" className="btn btn-primary btn-lg">
                <Zap size={18} /> Go to Dashboard <ArrowRight size={18} />
              </Link>
            ) : (
              <>
                <Link to="/signup" className="btn btn-primary btn-lg">
                  Start for Free <ArrowRight size={18} />
                </Link>
                <Link to="/login" className="btn btn-outline btn-lg">Sign In</Link>
              </>
            )}
          </div>

          {/* Trust line */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 24, flexWrap: 'wrap' }}>
            {['No credit card', 'Instant questions', 'AI-powered answers'].map(t => (
              <div key={t} style={{ display: 'flex', alignItems: 'center', gap: 6, color: 'var(--text-400)', fontSize: '0.875rem' }}>
                <CheckCircle size={14} color="#10b981" /> {t}
              </div>
            ))}
          </div>

          <div style={{ marginTop: 70, animation: 'bounce 2s infinite' }}>
            <ChevronDown size={24} color="var(--text-400)" style={{ margin: '0 auto' }} />
          </div>
        </div>
      </section>

      {/* ── STATS ── */}
      <section style={{ padding: '60px 0', borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)', background: 'var(--bg-800)' }}>
        <div className="container">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 32, textAlign: 'center' }}>
            {stats.map(s => (
              <div key={s.label}>
                <div style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontWeight: 800, fontFamily: 'Space Grotesk', background: 'linear-gradient(135deg, #a78bfa, #38bdf8)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>{s.value}</div>
                <div style={{ color: 'var(--text-300)', fontSize: '0.9rem', marginTop: 4 }}>{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section className="section" id="features">
        <div className="container">
          <div style={{ textAlign: 'center', marginBottom: 64 }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '6px 16px', borderRadius: 999, background: 'rgba(6,182,212,0.1)', border: '1px solid rgba(6,182,212,0.25)', marginBottom: 16 }}>
              <Star size={12} color="#06b6d4" /><span style={{ fontSize: '0.8rem', color: '#06b6d4', fontWeight: 600 }}>FEATURES</span>
            </div>
            <h2 style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontWeight: 800, letterSpacing: '-1px' }}>
              Everything You Need to<br /><span className="gradient-text">Land the Job</span>
            </h2>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 24 }}>
            {features.map(({ icon: Icon, title, desc, color }) => (
              <div key={title} className="card" style={{ cursor: 'default' }}>
                <div style={{ width: 48, height: 48, borderRadius: 12, background: `${color}20`, border: `1px solid ${color}40`, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 20 }}>
                  <Icon size={22} color={color} />
                </div>
                <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: 10 }}>{title}</h3>
                <p style={{ color: 'var(--text-300)', fontSize: '0.9rem', lineHeight: 1.7 }}>{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ── */}
      <section className="section" id="how-it-works" style={{ background: 'var(--bg-800)' }}>
        <div className="container">
          <div style={{ textAlign: 'center', marginBottom: 64 }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '6px 16px', borderRadius: 999, background: 'rgba(245,158,11,0.1)', border: '1px solid rgba(245,158,11,0.25)', marginBottom: 16 }}>
              <Zap size={12} color="#f59e0b" /><span style={{ fontSize: '0.8rem', color: '#f59e0b', fontWeight: 600 }}>HOW IT WORKS</span>
            </div>
            <h2 style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontWeight: 800, letterSpacing: '-1px' }}>
              From Zero to <span className="gradient-text-gold">Interview-Ready</span><br />in 4 Steps
            </h2>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 24 }}>
            {steps.map((s, i) => (
              <div key={s.num} className="card" style={{ textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
                <div style={{ fontSize: '4rem', fontWeight: 900, fontFamily: 'Space Grotesk', color: 'rgba(139,92,246,0.08)', lineHeight: 1, marginBottom: 8 }}>{s.num}</div>
                <div style={{ position: 'absolute', top: 20, left: '50%', transform: 'translateX(-50%)', width: 40, height: 40, borderRadius: 10, background: 'linear-gradient(135deg, #7c3aed, #06b6d4)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, color: 'white', fontFamily: 'Space Grotesk', fontSize: '0.85rem' }}>{i + 1}</div>
                <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: 10, marginTop: 8 }}>{s.title}</h3>
                <p style={{ color: 'var(--text-300)', fontSize: '0.875rem', lineHeight: 1.7 }}>{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="section" style={{ position: 'relative', overflow: 'hidden' }}>
        <div className="orb orb-purple" style={{ width: 600, height: 600, top: '-50%', left: '50%', transform: 'translateX(-50%)', opacity: 0.3 }} />
        <div className="container" style={{ position: 'relative', zIndex: 1, textAlign: 'center' }}>
          <h2 style={{ fontSize: 'clamp(2rem, 4vw, 3.5rem)', fontWeight: 900, letterSpacing: '-1.5px', marginBottom: 20 }}>
            Ready to <span className="gradient-text">Ace Your Interview?</span>
          </h2>
          <p style={{ color: 'var(--text-300)', fontSize: '1.1rem', marginBottom: 40, maxWidth: 500, margin: '0 auto 40px' }}>
            Join thousands of developers who've landed roles at top companies using PrepEdge AI.
          </p>
          <Link to="/signup" className="btn btn-primary btn-lg">
            <Sparkles size={18} /> Start Preparing Now <ArrowRight size={18} />
          </Link>
        </div>
      </section>

      <style>{`
        @keyframes fadeInDown { from { opacity: 0; transform: translateY(-20px); } to { opacity: 1; transform: translateY(0); } }
        @keyframes bounce { 0%,100% { transform: translateY(0); } 50% { transform: translateY(8px); } }
        @keyframes float-symbol { 
          0% { transform: translateY(0) rotate(0deg) scale(1); } 
          100% { transform: translateY(-25px) rotate(15deg) scale(1.1); } 
        }
        @keyframes fly-plane {
          0% { left: -10%; transform: translateY(0) scale(0.8); }
          50% { transform: translateY(-30px) scale(1); }
          100% { left: 110%; transform: translateY(-60px) scale(1.2); }
        }
      `}</style>
    </div>
  );
}
